name: langstats
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  # workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: peytonbrsmith/metrics@master
        with:
          # Your GitHub token
          filename: lang-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: no
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_skipped: metrics, webxrtesting
          plugin_languages_threshold: "2%"
          plugin_languages_indepth: true
          plugin_languages_categories: programming
          plugin_languages_limit: 0
          commits_authoring: peytonbrsmith, peytonbrsmith@gmail.com
          plugin_languages_ignored: none
