name: webmetrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  # workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: peytonbrsmith/metrics@master
        with:
          # Your GitHub token
          filename: webmetrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: metadata
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} # Optional but recommended
          plugin_pagespeed_detailed: yes                         # Print detailed audit metrics
          plugin_pagespeed_screenshot: yes                        # Display a screenshot of your website
          plugin_pagespeed_url: .user.website                    # Website to audit (defaults to your GitHub linked website)
